# wueasy - A Java Distributed Rapid Development Platform.
# Copyright (C) 2017-2019 wueasy.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

wueasy : 
  session: #session配置
    type: local #类型 local 本地session 默认，redis ，guava 
  file : 
    upload : #上传配置
      type: 1 #上传类型 1 本地上传 默认 ，2 腾讯对象存储 ，3 阿里云对象存储
      rootPath: /srv/www/app/wueasy/web/upload #文件上传根目录
      maxSize: 50 #文件最大大小，单位M
      httpAccessPath: http://upload.wueasy.com #http访问的路径
      funcNo: MALL2006,MALL2008
    cos : #腾讯对象存储配置
      secretId : 
      secretKey : 
      bucketName : test-1251238510 #bucket 的命名规则为{name}-{appid} ，此处填写的存储桶名称必须为此格式
      region : ap-shanghai #设置bucket的区域, COS地域的简称请参照 https://cloud.tencent.com/document/product/436/6224
#    cos : #阿里云对象存储配置
#      secretId : 
#      secretKey : 
#      bucketName : hao54 #bucket 的命名规则为{name} ，此处填写的存储桶名称必须为此格式
#      region :  https://oss-cn-hangzhou.aliyuncs.com #设置bucket的区域, COS地域的简称请参照 https://help.aliyun.com/document_detail/31837.html?spm=a2c4g.11186623.6.571.3ac87f5e7vtneC
  security :
    xss : #不需要xss清理的配置
     - funcNo : T1021,T1022 #功能号，多个逗号分隔
       field : content #字段，多个逗号分隔
     - funcNo : T1008,T1009 
       field : itemValue 
  datasource : 
    easyadmin : 
      mybatis:
        basePackage: com.wueasy.**.mapper
        mapperLocations: classpath*:mybatis/wueasy/**/*.xml
      connection: 
        url : jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username : easyadmin
        password : easyadmin
        #连接池配置
        initialSize : 30  #初始化大小
        minIdle : 30  #最小连接
        maxActive : 50  #最大连接
        maxWait : 60000  #配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis : 2000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis : 600000  #配置一个连接在池中最小生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis : 600000  #配置一个连接在池中最大生存的时间，单位是毫秒
        validationQuery : SELECT 1 from dual 
        testWhileIdle : true
        testOnBorrow : false
        testOnReturn : false
        keepAlive : true
  zipkin: #链路跟踪配置
    enabled: true #是否启用，默认false
    url: http://zipkin.wueasy.com:9411/api/v2/spans
  elk: #elk日志管理
    url: elk.wueasy.com:5000
#  localIp : 127.0.0.1 #指定本机ip地址
  zk : 
    servers : 127.0.0.1:2181
    sessionTimeout : 3000
    connectionTimeout : 5000
  bus : 
    #服务端配置
    server : 
      protocol: injvm
      port : 10200 #端口
      group : wueasy-admin #分组
      minWorkerThread : 20 #最小工作pool线程数
      maxWorkerThread : 50 #最大工作pool线程数
    #客户端配置
    client : 
      base : #默认客户端配置
        protocol: injvm
        group : wueasy-admin
        minClientConnection : 5 #client最小连接数
        maxClientConnection : 20 #client最大连接数
        requestTimeout : 60000 #请求超时时间(毫秒)
      taskClient : #定时任务客户端
        group : wueasy-task
        minClientConnection : 5 #client最小连接数
        maxClientConnection : 20 #client最大连接数
        requestTimeout : 60000 #请求超时时间(毫秒)
  job : #定时任务配置
    zkConnectString : ${wueasy.zk.servers} #注册中心字符串
    namespace : wueasy-task #注册中心命名空间
    digest :  #注册中心凭证